/**
 * Infrastructure Layer — null-object factories and helpers for:
 *   capabilities, manifest-validator, headless, wasm-kernel, generators
 */

import { createHash, createHmac } from 'node:crypto';

// ============================================================================
// Capabilities (algebraic capability tokens for per-agent permissions)
// ============================================================================

export function createNullCapabilityAlgebra() {
  return {
    grant(params) {
      return { id: `null-cap-${Date.now()}`, capabilityId: `null-cap-${Date.now()}`, granted: false };
    },
    restrict(capability, restrictions) { return capability; },
    delegate(capability, toAgentId, restrictions) { return capability; },
    expire(capabilityId) {},
    revoke(capabilityId, reason) {},
    attest(capabilityId, attestation) {},
    check(agentId, scope, resource, action, context) {
      return { allowed: true, reason: 'capabilities-disabled' };
    },
    getCapabilities(agentId) { return []; },
    getCapability(id) { return null; },
    getDelegationChain(capabilityId) { return []; },
    compose(cap1, cap2) { return cap1; },
    isSubset(inner, outer) { return true; },
  };
}

// ============================================================================
// Manifest Validator (agent admission control + risk scoring)
// ============================================================================

export function createNullManifestValidator() {
  return {
    validate(manifest) {
      return { valid: true, errors: [], warnings: [] };
    },
    computeRiskScore(manifest) { return 0; },
    selectLane(manifest, riskScore) { return 'standard'; },
    validateBudgets(manifest) { return { valid: true }; },
    validateToolPolicy(manifest) { return { valid: true }; },
    validateDataPolicy(manifest) { return { valid: true }; },
  };
}

export function createNullConformanceSuite() {
  return {
    addTrace(trace) {},
    run(evaluator) { return { passed: true, results: [], traces: 0 }; },
    getTraces() { return []; },
    createDefaultTraces() { return []; },
  };
}

// ============================================================================
// Headless Runner (CI/CD compliance test suite)
// ============================================================================

export function createNullHeadlessRunner() {
  return {
    setLedger(ledger) {},
    async runTask(task) {
      return {
        taskId: task?.id ?? 'null',
        passed: true,
        skipped: true,
        reason: 'headless-disabled',
        assertions: [],
        violations: [],
      };
    },
    async runSuite(tasks, tags) {
      return {
        passed: true,
        total: 0,
        passed_count: 0,
        failed: 0,
        skipped: tasks?.length ?? 0,
        results: [],
      };
    },
  };
}

// ============================================================================
// WASM Kernel (performance optimization — JS fallback is automatic upstream)
// ============================================================================

export function createNullWasmKernel() {
  // The real wasm-kernel has automatic JS fallback, so the null-object
  // just signals that we haven't opted into WASM acceleration.
  return {
    available: false,
    version: 'null-kernel',
    sha256(input) {
      return createHash('sha256').update(input).digest('hex');
    },
    hmacSha256(key, input) {
      return createHmac('sha256', key).update(input).digest('hex');
    },
    contentHash(jsonInput) {
      return createHash('sha256').update(jsonInput).digest('hex');
    },
    signEnvelope(key, envelopeJson) {
      return createHmac('sha256', key).update(envelopeJson).digest('hex');
    },
    verifyChain(chainJson, key) { return true; },
    scanSecrets(content) { return []; },
    detectDestructive(command) { return null; },
    batchProcess(ops) { return ops.map(() => ({ ok: true })); },
  };
}

// ============================================================================
// Generators (CLAUDE.md scaffolding — stateless utility)
// ============================================================================

export function createNullGenerators() {
  return {
    generateClaudeMd(profile) { return '# CLAUDE.md\n\nGenerated by guidance scaffolder.\n'; },
    generateClaudeLocalMd(local) { return '# CLAUDE.local.md\n'; },
    generateSkillMd(skill) { return `# ${skill?.name ?? 'Skill'}\n`; },
    generateAgentMd(agent) { return `# ${agent?.name ?? 'Agent'}\n`; },
    generateAgentIndex(agents) { return '# Agents\n'; },
    scaffold(options) { return { files: new Map() }; },
  };
}
